#!/bin/sh
# File generated by ocamlbuild

cd /Users/sword/Documents/SafetyProtocol/outputs

rm -f result.o
# Also clean the script itself
rm -f /Users/sword/Documents/SafetyProtocol/outputs/_build/sanitize.sh
